from falcor import *

def render_graph_PathTracerGraph():
    g = RenderGraph('PathTracerGraph')
    loadRenderPassLibrary('BSDFViewer.dll')
    loadRenderPassLibrary('AccumulatePass.dll')
    loadRenderPassLibrary('TemporalDelayPass.dll')
    loadRenderPassLibrary('Antialiasing.dll')
    loadRenderPassLibrary('BlitPass.dll')
    loadRenderPassLibrary('CSM.dll')
    loadRenderPassLibrary('DebugPasses.dll')
    loadRenderPassLibrary('DepthPass.dll')
    loadRenderPassLibrary('ErrorMeasurePass.dll')
    loadRenderPassLibrary('FLIPPass.dll')
    loadRenderPassLibrary('WhittedRayTracer.dll')
    loadRenderPassLibrary('PixelInspectorPass.dll')
    loadRenderPassLibrary('ForwardLightingPass.dll')
    loadRenderPassLibrary('GBuffer.dll')
    loadRenderPassLibrary('SkyBox.dll')
    loadRenderPassLibrary('ImageLoader.dll')
    loadRenderPassLibrary('MegakernelPathTracer.dll')
    loadRenderPassLibrary('MinimalPathTracer.dll')
    loadRenderPassLibrary('NNPathGuiding.dll')
    loadRenderPassLibrary('OptixDenoiser.dll')
    loadRenderPassLibrary('PassLibraryTemplate.dll')
    loadRenderPassLibrary('SceneDebugger.dll')
    loadRenderPassLibrary('SimplePostFX.dll')
    loadRenderPassLibrary('SSAO.dll')
    loadRenderPassLibrary('TestPasses.dll')
    loadRenderPassLibrary('SVGFPass.dll')
    loadRenderPassLibrary('ToneMapper.dll')
    loadRenderPassLibrary('Utils.dll')
    loadRenderPassLibrary('VisualizeVMF.dll')
    AccumulatePass = createPass('AccumulatePass', {'enabled': False, 'autoReset': True, 'precisionMode': AccumulatePrecision.Single, 'subFrameCount': 0, 'maxAccumulatedFrames': 0})
    g.addPass(AccumulatePass, 'AccumulatePass')
    AccumulatePassIrr = createPass('AccumulatePass', {'enabled': False, 'autoReset': True, 'precisionMode': AccumulatePrecision.Single, 'subFrameCount': 0, 'maxAccumulatedFrames': 0})
    g.addPass(AccumulatePassIrr, 'AccumulatePassIrr')
    VisualizeVMFPass = createPass('VisualizeVMF')
    g.addPass(VisualizeVMFPass, 'VisualizeVMFPass')
    ToneMappingPass = createPass('ToneMapper', {'useSceneMetadata': True, 'exposureCompensation': 0.0, 'autoExposure': False, 'filmSpeed': 100.0, 'whiteBalance': False, 'whitePoint': 6500.0, 'operator': ToneMapOp.Aces, 'clamp': True, 'whiteMaxLuminance': 1.0, 'whiteScale': 11.199999809265137, 'fNumber': 1.0, 'shutter': 1.0, 'exposureMode': ExposureMode.AperturePriority})
    g.addPass(ToneMappingPass, 'ToneMappingPass')
    GBufferRT = createPass('GBufferRT', {'samplePattern': SamplePattern.Stratified, 'sampleCount': 16, 'useAlphaTest': True, 'adjustShadingNormals': True, 'forceCullMode': False, 'cull': CullMode.CullBack, 'texLOD': TexLODMode.Mip0, 'useTraceRayInline': False})
    g.addPass(GBufferRT, 'GBufferRT')
    SideBySidePass = createPass('SideBySidePass', {'splitLocation': -1.0, 'showTextLabels': False, 'leftLabel': 'Left side', 'rightLabel': 'Right side'})
    g.addPass(SideBySidePass, 'SideBySidePass')
    NNPathGuiding = createPass('NNPathGuiding', {'params': PathTracerParams(samplesPerPixel=1, lightSamplesPerVertex=1, maxBounces=0, maxNonSpecularBounces=0, useVBuffer=0, useAlphaTest=1, adjustShadingNormals=0, forceAlphaOne=1, clampSamples=0, clampThreshold=10.0, specularRoughnessThreshold=0.25, useBRDFSampling=0, useNEE=0, useMIS=0, misHeuristic=1, misPowerExponent=2.0, useRussianRoulette=0, probabilityAbsorption=0.20000000298023224, useFixedSeed=0, useNestedDielectrics=1, useLightsInDielectricVolumes=0, disableCaustics=0, rayFootprintMode=0, rayConeMode=2, rayFootprintUseRoughness=0), 'sampleGenerator': 1, 'emissiveSampler': EmissiveLightSamplerType.LightBVH, 'uniformSamplerOptions': LightBVHSamplerOptions(buildOptions=LightBVHBuilderOptions(splitHeuristicSelection=SplitHeuristic.BinnedSAOH, maxTriangleCountPerLeaf=10, binCount=16, volumeEpsilon=0.0010000000474974513, splitAlongLargest=False, useVolumeOverSA=False, useLeafCreationCost=True, createLeavesASAP=True, allowRefitting=True, usePreintegration=True, useLightingCones=True), useBoundingCone=True, useLightingCone=True, disableNodeFlux=False, useUniformTriangleSampling=True, solidAngleBoundMethod=SolidAngleBoundMethod.Sphere)})
    g.addPass(NNPathGuiding, 'NNPathGuiding')
    ErrorMeasurePass = createPass('ErrorMeasurePass', {'ReferenceImagePath': 'D:\\Dominik\\Studium\\Thesis\\results\\CornellBox\\20230309_irradianceReference\\indirect2_reference.AccumulatePass.output.341186.exr', 'MeasurementsFilePath': 'D:\\Dominik\\Studium\\Thesis\\results\\CornellBox\\20230314_errorMeasure\\mse.csv', 'IgnoreBackground': False, 'ComputeSquaredDifference': True, 'ComputeAverage': False, 'UseLoadedReference': True, 'ReportRunningError': False, 'RunningErrorSigma': 0.9950000047683716, 'SelectedOutputId': OutputId.Source})
    g.addPass(ErrorMeasurePass, 'ErrorMeasurePass')
    FLIPPass = createPass('FLIPPass', {'enabled': True, 'useMagma': True, 'monitorWidthPixels': 1920, 'monitorWidthMeters': 0.5, 'monitorDistanceMeters': 0.699999988079071, 'calculatePerFrameFLIP': True, 'useRealMonitorInfo': False, 'MeasurementsFilePath': 'D:\\Dominik\\Studium\\Thesis\\results\\CornellBox\\20230314_errorMeasure\\flip.csv'})
    g.addPass(FLIPPass, 'FLIPPass')
    ImageLoader = createPass('ImageLoader', {'filename': 'D:\\Dominik\\Studium\\Thesis\\results\\CornellBox\\20230309_irradianceReference\\indirect2_reference.AccumulatePass.output.341186.exr', 'mips': False, 'srgb': True, 'arrayIndex': 0, 'mipLevel': 0})
    g.addPass(ImageLoader, 'ImageLoader')
    g.addEdge('GBufferRT.vbuffer', 'NNPathGuiding.vbuffer')
    g.addEdge('GBufferRT.posW', 'NNPathGuiding.posW')
    g.addEdge('GBufferRT.normW', 'NNPathGuiding.normalW')
    g.addEdge('GBufferRT.tangentW', 'NNPathGuiding.tangentW')
    g.addEdge('GBufferRT.faceNormalW', 'NNPathGuiding.faceNormalW')
    g.addEdge('GBufferRT.viewW', 'NNPathGuiding.viewW')
    g.addEdge('GBufferRT.diffuseOpacity', 'NNPathGuiding.mtlDiffOpacity')
    g.addEdge('GBufferRT.specRough', 'NNPathGuiding.mtlSpecRough')
    g.addEdge('GBufferRT.emissive', 'NNPathGuiding.mtlEmissive')
    g.addEdge('GBufferRT.matlExtra', 'NNPathGuiding.mtlParams')
    g.addEdge('NNPathGuiding.color', 'AccumulatePass.input')
    g.addEdge('NNPathGuiding.irradiance', 'AccumulatePassIrr.input')
    g.addEdge('AccumulatePass.output', 'ToneMappingPass.src')
    g.addEdge('AccumulatePass.output', 'SideBySidePass.leftInput')
    g.addEdge('VisualizeVMFPass.mu', 'SideBySidePass.rightInput')
    g.addEdge('NNPathGuiding.vmf', 'VisualizeVMFPass.vmf')
    g.addEdge('AccumulatePass.output', 'ErrorMeasurePass.Source')
    g.addEdge('ImageLoader.dst', 'ErrorMeasurePass.Reference')
    g.addEdge('AccumulatePass.output', 'FLIPPass.inputA')
    g.addEdge('ImageLoader.dst', 'FLIPPass.inputB')
    g.markOutput('ToneMappingPass.dst')
    g.markOutput('AccumulatePass.output')
    g.markOutput('AccumulatePassIrr.output')
    g.markOutput('VisualizeVMFPass.mu')
    g.markOutput('VisualizeVMFPass.kappa')
    g.markOutput('NNPathGuiding.luminance')
    g.markOutput('NNPathGuiding.irradiance')
    g.markOutput('SideBySidePass.output')
    g.markOutput('ErrorMeasurePass.Output')
    g.markOutput('FLIPPass.output')
    return g

PathTracerGraph = render_graph_PathTracerGraph()
try: m.addGraph(PathTracerGraph)
except NameError: None
